version: '3'
services:

  app:
    container_name: "api"
    build:
      dockerfile: Dockerfile
    stop_signal: SIGKILL
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - X_API_KEY=${X_API_KEY}
      - EVENTS_API_URL=${EVENTS_API_URL}
    ports:
      - '5000:5000'
    expose:
      - 5000
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    container_name: "postgres"
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 25s
      retries: 5
